### PR TITLE
use multi stage build

### PR DESCRIPTION
**Pull request by inductor**

### CODE REVIEW

**Comment by onokatio** [comment]
Dockerize is used for waiting for other services. So I think we can stop to use dockerize and use [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) instead of it.

https://github.com/weseek/growi-docker-compose/blob/68adada4a999e5e3214de013fba6c3b78f75e169/docker-compose.yml#L29..L32

**Comment by yuki-takei** [comment]
@inductor Sorry, a conflict occurred by merging https://github.com/weseek/growi-docker-compose/pull/65. Could you resolve it?

**Comment by yuki-takei** [comment]
@onokatio Thank you for your contribution.
Would you send us another PR?

**Comment by yuki-takei** [comment]
Taken over at https://github.com/weseek/growi-docker-compose/pull/72

**Pull request closed without merging**
